#include "defs.h"

int scan(struct token* t);
struct ASTnode *mkastnode(int op, struct ASTnode *left,
			  struct ASTnode *right, int intvalue);
struct ASTnode *mkastleaf(int op, int intvalue);
struct ASTnode *mkastunary(int op, struct ASTnode *left, int intvalue);
struct ASTnode *constructBinExp();
int interpretAST(struct ASTnode *n);
int genAST(struct ASTnode* n, int);
int arithop(int);
struct ASTnode* binexpr(int);
struct ASTnode* constructLiteralNode();
void freeall_registers();
void generatecode(struct ASTnode* n);
void cgpreamble();
void cgpostamble();
int cgloadint(int value);
int cgadd(int r1, int r2);
int cgsub(int r1, int r2);
int cgmul(int r1, int r2);
int cgdiv(int r1, int r2);
void cgprintint(int r);
void cgglobsym(char*);
int cgstorglob(int r, char* identifier);
int cgloadglob(char* identifier);
void cgglobsym(char* sym);
void match(int, char*);
void semi();
void ident();
void genpreamble();
void genpostamble();
void genfreeregs();
void genprintint(int);
void genglobsym(char *s);
void statements();
void fatal(char*);
void fatals(char*, char*);
void fatald(char*, int);
void fatalc(char*, int);
int findglob(char*);
int addglob(char*);
